version: '3.4'

services:
  users.api:
    image: ${DOCKER_REGISTRY-}usersapi
    build:
      context: .
      dockerfile: Users.Api/Dockerfile
    depends_on:
    - db
    - seq

  db:
    image: mcr.microsoft.com/mssql/server    
    environment:       
        - SA_PASSWORD=Pass@word
        - ACCEPT_EULA=Y
    ports:
    - "5533:1433"

  seq:
    image: datalust/seq  
    environment:
        - ACCEPT_EULA=Y
    restart: unless-stopped
    volumes:
        - ./seq-data:/data
    ports:
        - "5341:80"